library(grImport)
PostScriptTrace("grey-heron.eps")
PostScriptTrace("aves.eps")
PostScriptTrace("fly.eps")
PostScriptTrace("rabbit.eps")
PostScriptTrace("bird-alpine-chough.eps")
PostScriptTrace("deer.eps")
PostScriptTrace("chinook.eps")
