CACHE = ~/Dropbox/heavy-tails/cache

sendCacheToDropbox:
	cp gpdd-clean.rds $(CACHE)
	cp gomp-base-hat.rds $(CACHE)
	cp logistic-hat.rds $(CACHE)
	cp gomp-ar1-hat.rds $(CACHE)
	cp gomp-obs-0.2-hat.rds $(CACHE)
	cp rate-hat.rds $(CACHE)
	cp gomp-base-weaker-hat.rds $(CACHE)
	cp gomp-base-stronger-hat.rds $(CACHE)
	cp gomp-base-mean-sd.rds $(CACHE)
