cp ../analysis/gomp-comparison.pdf fig-s1.pdf
cp ../analysis/gomp-prior-comparison.pdf fig-s2.pdf
cp ../analysis/t-dist-sampling-sim-prior-exp0point01.pdf fig-s3a.pdf
cp ../analysis/t-dist-sampling-sim-sigma-prior-exp0point01.pdf fig-s3b.pdf
cp ../analysis/sim-gompertz-median-dist.pdf fig-s4a.pdf
cp ../analysis/sim-gompertz-p10.pdf fig-s4b.pdf
cp ../analysis/correlates-p10.pdf fig-s5.pdf
cp ../analysis/skew-t-illustration.pdf fig-s6a.pdf
cp ../analysis/skewness-vs-nu.pdf fig-s6b.pdf
cp ../analysis/heavy-skew-projections-ggplot.pdf fig-s7.pdf
cp ../analysis/priors-gomp-base.pdf fig-s8.pdf

cp ../analysis/sparks/6528.pdf .
cp ../analysis/sparks/7115.pdf .
cp ../analysis/sparks/10127.pdf .
cp ../analysis/sparks/9382.pdf .
cp ../analysis/sparks/10128.pdf .
cp ../analysis/sparks/10007.pdf .
cp ../analysis/sparks/20579.pdf .
cp ../analysis/sparks/9655.pdf .
cp ../analysis/sparks/1235.pdf .
cp ../analysis/sparks/9667.pdf .
cp ../analysis/sparks/10113.pdf .
cp ../analysis/sparks/9679.pdf .
cp ../analysis/sparks/20527.pdf .
cp ../analysis/sparks/10039.pdf .
cp ../analysis/sparks/10162.pdf .
cp ../analysis/sparks/7099.pdf .
cp ../analysis/sparks/9503.pdf .
cp ../analysis/sparks/2778.pdf .
cp ../analysis/sparks/9659.pdf .
